In [1]:
import numpy as np

In [6]:
arr = np.arange(0, 50, 1).reshape(10, 5)

In [10]:
print("Original Array")
print(arr)
print("Transposed Array")
print(arr.T) # arr.T or arr.transpose()

Original Array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
Transposed Array
[[ 0  5 10 15 20 25 30 35 40 45]
 [ 1  6 11 16 21 26 31 36 41 46]
 [ 2  7 12 17 22 27 32 37 42 47]
 [ 3  8 13 18 23 28 33 38 43 48]
 [ 4  9 14 19 24 29 34 39 44 49]]


In [18]:
print(np.exp(arr))    # get exponent of every element
print(np.square(arr)) # get square of every element
print(np.sqrt(arr))   # get square root of every element
print(np.cbrt(arr))   # get the cube root of every element
# np.add(arr1, arr2)  # add corresponding elements of two arrays
# np.substract(arr1, arr2) # substract corresponding elements of two arrays

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
  8.10308393e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05
  1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07 6.56599691e+07
  1.78482301e+08]
 [4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09
  2.64891221e+10]
 [7.20048993e+10 1.95729609e+11 5.32048241e+11 1.44625706e+12
  3.93133430e+12]
 [1.06864746e+13 2.90488497e+13 7.89629602e+13 2.14643580e+14
  5.83461743e+14]
 [1.58601345e+15 4.31123155e+15 1.17191424e+16 3.18559318e+16
  8.65934004e+16]
 [2.35385267e+17 6.39843494e+17 1.73927494e+18 4.72783947e+18
  1.28516001e+19]
 [3.49342711e+19 9.49611942e+19 2.58131289e+20 7.01673591e+20
  1.90734657e+21]]
[[   0    1    4    9   16]
 [  25   36   49   64   81]
 [ 100  121  144  169  196]
 [ 225  256  289  324  361]
 [ 400  441  484  529  576]
 [ 625  676  729  784  841]
 [ 900  961 1024 1089 1156]
 [1

## Numpy where function

In [19]:
arr1 =  np.array([10, 20, 30, 40])
arr2 = np.array([500, 600, 700, 800])

cond = np.array([False, True, False, True]) # Create an array with bool operators
res = np.where(cond, arr1, arr2) # apply the where condition
print(res)

[500  20 700  40]


## Array loading and saving

In [24]:
arr1 = np.random.randn(7)
print("Original Array")
print(arr1)

np.save("arr1_saved", arr1) # save the array as file (.npy)

arr2 = np.load("arr1_saved.npy") # Load the saved array from file

print("\nArray loaded from file")
print(arr2)

Original Array
[-0.33186079 -0.10341472 -0.55859316 -1.06244043 -1.14209928 -0.43120192
  1.0256367 ]

Array loaded from file
[-0.33186079 -0.10341472 -0.55859316 -1.06244043 -1.14209928 -0.43120192
  1.0256367 ]
